/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceToggle: typeof import('./../../node_modules/.pnpm/@project-trans+vitepress-theme-project-trans@0.4.1727360260_@algolia+client-search@5.6.1_@bab_ybrdi2wrdx3tosdt2a2lwj6t5a/node_modules/@project-trans/vitepress-theme-project-trans/dist/components/AppearanceToggle.vue')['default']
    AppFooter: typeof import('./../../node_modules/.pnpm/@project-trans+vitepress-theme-project-trans@0.4.1727360260_@algolia+client-search@5.6.1_@bab_ybrdi2wrdx3tosdt2a2lwj6t5a/node_modules/@project-trans/vitepress-theme-project-trans/dist/components/AppFooter.vue')['default']
    AppSBox: typeof import('./../../node_modules/.pnpm/@project-trans+vitepress-theme-project-trans@0.4.1727360260_@algolia+client-search@5.6.1_@bab_ybrdi2wrdx3tosdt2a2lwj6t5a/node_modules/@project-trans/vitepress-theme-project-trans/dist/components/AppSBox.vue')['default']
    ArticlesMenu: typeof import('./../../node_modules/.pnpm/@project-trans+vitepress-theme-project-trans@0.4.1727360260_@algolia+client-search@5.6.1_@bab_ybrdi2wrdx3tosdt2a2lwj6t5a/node_modules/@project-trans/vitepress-theme-project-trans/dist/components/ArticlesMenu.vue')['default']
    CopyrightInfo: typeof import('./../../node_modules/.pnpm/@project-trans+vitepress-theme-project-trans@0.4.1727360260_@algolia+client-search@5.6.1_@bab_ybrdi2wrdx3tosdt2a2lwj6t5a/node_modules/@project-trans/vitepress-theme-project-trans/dist/components/CopyrightInfo.vue')['default']
    HomeContent: typeof import('./../../node_modules/.pnpm/@project-trans+vitepress-theme-project-trans@0.4.1727360260_@algolia+client-search@5.6.1_@bab_ybrdi2wrdx3tosdt2a2lwj6t5a/node_modules/@project-trans/vitepress-theme-project-trans/dist/components/HomeContent.vue')['default']
    PageInfo: typeof import('./../../node_modules/.pnpm/@project-trans+vitepress-theme-project-trans@0.4.1727360260_@algolia+client-search@5.6.1_@bab_ybrdi2wrdx3tosdt2a2lwj6t5a/node_modules/@project-trans/vitepress-theme-project-trans/dist/components/PageInfo.vue')['default']
    ReadingTime: typeof import('./../../node_modules/.pnpm/@project-trans+vitepress-theme-project-trans@0.4.1727360260_@algolia+client-search@5.6.1_@bab_ybrdi2wrdx3tosdt2a2lwj6t5a/node_modules/@project-trans/vitepress-theme-project-trans/dist/components/ReadingTime.vue')['default']
  }
}
